name: kawaii_chat
description: "A new Flutter project for kawaii chat."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^3.0.2
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.10
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.0.2
  json_serializable: ^6.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.1.6
  build_runner: ^2.1.10

flutter_icons:
  android: true
  ios: true
  image_path_android: asset/image/launcher_icon/message_small.png
  image_path_ios: asset/image/launcher_icon/message_small.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: asset/image/launcher_icon/message_small.png
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#FFFFFF"
  image: asset/image/launcher_icon/message_big.png
  color_dark: "#2F2F2F"
  image_dark: asset/image/launcher_icon/message_big.png
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  android12: true

flutter:
  uses-material-design: true
  assets:
    - asset/

  fonts:
    - family: Nunito
      fonts:
        - asset: asset/fonts/Nunito-ExtraLight.ttf
          weight: 100
        - asset: asset/fonts/Nunito-Light.ttf
          weight: 300
        - asset: asset/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: asset/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: asset/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: asset/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: asset/fonts/Nunito-ExtraBold.ttf
          weight: 900
