// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG_8OMSo3PdZZKDVhbuXiaouxx0L2YV2Q',
    appId: '1:647707730459:web:30bb6756bb12eb7e990ebe',
    messagingSenderId: '647707730459',
    projectId: 'kawaii-chat-88920',
    authDomain: 'kawaii-chat-88920.firebaseapp.com',
    storageBucket: 'kawaii-chat-88920.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcuKsUxIHHLIgs_u2EI9RxOf-HQzyS9xw',
    appId: '1:647707730459:android:1112a8efe83f7b3e990ebe',
    messagingSenderId: '647707730459',
    projectId: 'kawaii-chat-88920',
    storageBucket: 'kawaii-chat-88920.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ-DSfKppC3UtSFZS43ZlELwxTxqQaVgo',
    appId: '1:647707730459:ios:d35fb65ceb671064990ebe',
    messagingSenderId: '647707730459',
    projectId: 'kawaii-chat-88920',
    storageBucket: 'kawaii-chat-88920.appspot.com',
    iosClientId: '647707730459-ecfdn8td1n2akpnlid46232hr8laq93q.apps.googleusercontent.com',
    iosBundleId: 'com.example.kawaiiChat',
  );
}
